account_credentials/account_credentials/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.redirect_home, name='home')
]

account_credentials/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('update_password/', views.ChangeUserPassword.as_view(), name='update_password'),
    path('<int:pk>/update_profile/', views.ChangeProfile.as_view(), name='update_profile')
]

account_credentials/accounts/models.py
from django.db import models

# Create your models here.

account_credentials/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import generic


class CustomUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(CustomUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UpdateUserProfile(UserChangeForm):

    class Meta:
        model = User
        fields = ("username", "email")

    def save(self, commit=True):
        user = super(UpdateUserProfile, self).save(commit=False)
        if commit:
            user.save()
        return user

account_credentials/account_credentials/views.py
from django.shortcuts import render


def redirect_home(request):
    return render(request, template_name="accounts/homepage.html")

account_credentials/accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserForm, UpdateUserProfile
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.models import User


def home(request):
    return render(request, template_name='accounts/homepage.html')


class RegisterView(generic.CreateView):
    form_class = CustomUserForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/register.html'


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, 'Login successful!')
                return redirect('accounts:home')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid username or password.')
    form = AuthenticationForm()
    return render(request, template_name='accounts/login.html', context={'form': form})


def user_logout(request):
    logout(request)
    return redirect('accounts:home')


class ChangeUserPassword(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('accounts:home')
    template_name = 'accounts/update_password.html'


class ChangeProfile(generic.UpdateView):
    model = User
    form_class = UpdateUserProfile
    success_url = reverse_lazy('accounts:home')
    template_name = 'accounts/update_profile.html'

account_credentials/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{% block title %}{% endblock%}</title>
  </head>
 <body>

    {% block content %}

    {% endblock %}

  </body>
</html>

account_credentials/accounts/templates/accounts/homepage.html
{% extends 'accounts/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <style>
      ul { list-style: none;}
      a {text-decoration-line: none;}
    </style>

<div >
    <h2>Home Page</h2>
    {% if user.is_authenticated %}
    <ul style="list-style:{{none}}">
        <li><a href="{% url 'accounts:update_password' %}" >Change Password</a></li>
        <li><a href="{% url 'accounts:update_profile' user.id %}" >Change Username/Email</a></li>
        <li><a href="{% url 'accounts:logout' %}" >Logout</a></li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'accounts:register' %}" >Register</a></li>
        <li><a href="{% url 'accounts:login' %}" >Login</a></li>
    </ul>
    {% endif %}

</div>

{% endblock %}

account_credentials/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}<h1>Registration Page</h1>{% endblock %}

{% block content %}

<div >
    <h1>Login</h1>
    <form method="Post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
</div>

{% endblock %}

account_credentials/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block title %}Registration Page{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div >
    <h1>Register</h1>
    <form method="Post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
</div>

{% endblock %}

account_credentials/accounts/templates/accounts/update_password.html
{% extends 'accounts/base.html' %}

{% block title %}Update Password{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div >
    <h1>Update Password</h1>
    <form method="Post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Update Password</button>
    </form>
</div>

{% endblock %}

account_credentials/accounts/templates/accounts/update_profile.html
{% extends 'accounts/base.html' %}

{% block title %}Update Profile{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div >
    <h1>Update Profile</h1>
    <form method="Post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Update Profile</button>
    </form>
</div>

{% endblock %}